<h2>Sign up</h2>
<div class="col">
	<?php if($this->errorMessage): ?>
		<p class="form_error"><?= $this->errorMessage ?></p>
	<?php endif; ?>
	<?php echo $this->registerForm; ?>
</div>
<div class="col">
	<p>Welcome to The Beer IOU project.</p>
	<p>By signing up you will never ever forget whom you owe beer to, but more importantly who owes <b>you</b> beer!</p>
	<p>Small favor, big favor, saving life stuff, any excuse is good to say the words "I owe you a (multiple) beer(s)".</p>
	<p>Keep track of who, when and why through this simple site</p>
	<p>Have fun, drink responsibly, and don't drink and drive!!!!</p>
</div>
<div class="clearfix"></div>